export const TOGGLE_PREVIEW = 'TOGGLE_PREVIEW'

export const EDIT_MARKDOWN = 'EDIT_MARKDOWN'

export const TOGGLE_SAVEFILE = 'TOGGLE_SAVEFILE'

export const SAVE_NEWFILE = 'SAVE_NEWFILE'

export const REMOVE_FILE = 'REMOVE_FILE'

export const TOGGLE_BROWSE = 'TOGGLE_BROWSE'

export const LOAD_LOCALFILES = 'LOAD_LOCALFILES'

export const FETCH_HACKERNEWS_SUCCESS = 'FETCH_HACKERNEWS_SUCCESS'

export const FETCH_GITHUB_SUCCESS = 'FETCH_GITHUB_SUCCESS'

export const FETCH_V2EX_HOT_SUCCESS = 'FETCH_V2EX_HOT_SUCCESS'

export const FETCH_V2EX_TOPIC_SUCCESS = 'FETCH_V2EX_TOPIC_SUCCESS'

export const FETCH_V2EX_TOPICS_SUCCESS = 'FETCH_V2EX_TOPICS_SUCCESS'

export const CLEAN_TOPIC_CACHE = 'CLEAN_TOPIC_CACHE'
