export const TOGGLE_PREVIEW = "TOGGLE_PREVIEW";

export const EDIT_MARKDOWN = "EDIT_MARKDOWN";

export const TOGGLE_SAVEFILE = "TOGGLE_SAVEFILE";

export const SAVE_NEWFILE = "SAVE_NEWFILE";

export const TOGGLE_BROWSE = "TOGGLE_BROWSE";

export const LOAD_LOCALFILES = "LOAD_LOCALFILES";

